### ISSUE TITLE
Migrate to Tokio 1.0

### ISSUE THREAD

**Issue by mraerino** [launchdarkly/rust-server-sdk#1]
**Is your feature request related to a problem? Please describe.**

In order to use the SDK in production it would be great if it used the latest Tokio release.

**Describe the solution you'd like**

Migrate to the latest releases of Tokio & Reqwest.

I gave this a stab earlier after finishing https://github.com/launchdarkly/rust-eventsource-client/pull/5.
It's mostly pretty doable, but refactoring the batch event processor turned out to be pretty hard. It might be preferable to rewrite it from scratch.

What is the general idea for these things that are running something in a background task?
Should the SDK user provide a runtime to spawn them on? For my own usecases i'd prefer that, but i could imagine creating new new runtime in its own thread instead. Users could choose which one they want.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by keelerm84** [comment]
With the latest beta release, we are now targeting Tokio 1.2. We will be looking at bumping dependencies before the GA release but for now, I think we can call this issue resolved.
