### ISSUE TITLE
Calling `close()` on an offline mode client prints an error message

### ISSUE THREAD

**Issue by killpack** [launchdarkly/rust-server-sdk#15]
**Describe the bug**
If you call `close()` on a `Client` that is configured to run in offline mode, it prints an error message (on line 299):
https://github.com/launchdarkly/rust-server-sdk/blob/2f1f24a64465854d5665d17d92647e4e382126a4/launchdarkly-server-sdk/src/client.rs#L295-L305
That might be fine for `Client`s that are always configured to run in offline mode- you can just avoid calling `close()` on them. But it's annoying for `Client`s that can be configured to run in either offline or online mode. 

Additionally, because `Client` doesn't expose its `offline` property, there's no way for me to do something like this:
```rust
if !client.offline {
    client.close();
}
```

**To reproduce**
- Configure a client in offline mode
- Call `close()` on it
- See an error message: `Error: Failed to shutdown client appropriately: channel closed`

**Expected behavior**
Calling `close()` on an offline client should not print an error message.
Alternatively, I should be able to know whether is client was configured to run in offline mode (this could be as simple as making the `offline` property on `Client` `pub`), so that I can avoid calling `close()` on it without having to manage some additional piece of state in my application.

**SDK version**
1.0.0-beta.3

**Language version, developer tools**
Rust 2021 edition, rustc 1.60.0

**OS/platform**
I'm running on MacOS 12.3.1, but I don't think this is platform-specific.

**Comment by keelerm84** [comment]
Thank for you for the detailed bug report. I have filed this internally as `sc-160711`. We will notify you here as soon as we have a resolution available for you.

**Comment by keelerm84** [comment]
This should be resolved in the `1.0.0-beta.4` release.
