### ISSUE TITLE
Toolchain no longer needs to be pinned for coverage

### ISSUE THREAD

**Issue by iamwacko** [launchdarkly/rust-server-sdk#17]
**Is your feature request related to a problem? Please describe.**
Currently running coverage.sh will install nightly-2022-01-09. This is unnecessary, as https://github.com/rust-lang/rust/issues/79645 and https://github.com/taiki-e/cargo-llvm-cov/issues/128 are closed.

**Describe the solution you'd like**
Remove the parts of coverage.sh relating to adding  

**Describe alternatives you've considered**
There aren't really any alternatives

**Additional context**
This doesn't really directly affect me, but I thought you guys should know.

**Comment by cwaldren-ld** [comment]
Hey @iamwacko , we appreciate the notice. This has been resolved internally and will be fixed in the next release.
