### ISSUE TITLE
Implement all error types using enums and thiserror

### ISSUE THREAD

**Issue by mraerino** [launchdarkly/rust-server-sdk#3]
**Is your feature request related to a problem? Please describe.**

For people using this library it would be awesome if all error types implemented `Debug` & `Display` so it's easy to wrap them in our own code.

**Describe the solution you'd like**

If all parts of the code defined their error types using enums they could derive [`thiserror::Error`](https://docs.rs/thiserror/).

This is a very approachable pattern for maintainers of the SDK as well as users.

**Describe alternatives you've considered**
n/a

**Additional context**
You can see a bunch of those in my take on an SDK: https://github.com/mraerino/launchdarkly-rust-sdk-experimental/search?q=thiserror%3A%3AError

**Comment by keelerm84** [comment]
Thank you for the suggestion. The latest beta release of the SDK takes advantage of thiserror::Error as you suggested!
