### ISSUE TITLE
Including sdk in project causes cryptic compilation errors

### ISSUE THREAD

**Issue by parallaxisjones** [launchdarkly/rust-server-sdk#31]
**Describe the bug**
Including the Launch Darkly SDK in our rust bin project produces compilation errors. 

Using the latest publish crate `launchdarkly-server-sdk = "1.0.0"`

**To reproduce**
`$ cargo add launchdarkly-server-sdk`
`$ cargo check`
**Expected behavior**
The expectation is to use the launch darkly SDK in rust server code that needs feature flags

**Logs**
```bash
error[E0659]: `parse_quote_spanned` is ambiguous
   --> /Users/pkearfott/.cargo/registry/src/github.com-1ecc6299db9ec823/pin-project-internal-0.4.28/src/pin_project/derive.rs:865:67
    |
865 |                 proj_generics.make_where_clause().predicates.push(parse_quote_spanned! { span =>
    |                                                                   ^^^^^^^^^^^^^^^^^^^ ambiguous name
    |
    = note: ambiguous because of a conflict between a `macro_rules` name and a non-`macro_rules` name from another module
note: `parse_quote_spanned` could refer to the macro defined here
   --> /Users/pkearfott/.cargo/registry/src/github.com-1ecc6299db9ec823/pin-project-internal-0.4.28/src/utils.rs:23:1
    |
23  | / macro_rules! parse_quote_spanned {
24  | |     ($span:expr => $($tt:tt)*) => {
25  | |         syn::parse2(quote::quote_spanned!($span => $($tt)*)).unwrap_or_else(|e| panic!("{}", e))
26  | |     };
27  | | }
    | |_^
note: `parse_quote_spanned` could also refer to the macro imported here
   --> /Users/pkearfott/.cargo/registry/src/github.com-1ecc6299db9ec823/pin-project-internal-0.4.28/src/pin_project/derive.rs:7:5
    |
7   |     *,
    |     ^
    = help: use `self::parse_quote_spanned` to refer to this macro unambiguously

error[E0659]: `parse_quote_spanned` is ambiguous
   --> /Users/pkearfott/.cargo/registry/src/github.com-1ecc6299db9ec823/pin-project-internal-0.4.28/src/pinned_drop.rs:108:21
    |
108 |             *path = parse_quote_spanned! { path.span() =>
    |                     ^^^^^^^^^^^^^^^^^^^ ambiguous name
    |
    = note: ambiguous because of a conflict between a `macro_rules` name and a non-`macro_rules` name from another module
note: `parse_quote_spanned` could refer to the macro defined here
   --> /Users/pkearfott/.cargo/registry/src/github.com-1ecc6299db9ec823/pin-project-internal-0.4.28/src/utils.rs:23:1
    |
23  | / macro_rules! parse_quote_spanned {
24  | |     ($span:expr => $($tt:tt)*) => {
25  | |         syn::parse2(quote::quote_spanned!($span => $($tt)*)).unwrap_or_else(|e| panic!("{}", e))
26  | |     };
27  | | }
    | |_^
note: `parse_quote_spanned` could also refer to the macro imported here
   --> /Users/pkearfott/.cargo/registry/src/github.com-1ecc6299db9ec823/pin-project-internal-0.4.28/src/pinned_drop.rs:3:50
    |
3   | use syn::{spanned::Spanned, visit_mut::VisitMut, *};
    |                                                  ^
    = help: use `self::parse_quote_spanned` to refer to this macro unambiguously
```

**SDK version**
`launchdarkly-server-sdk = "1.0.0"`

**Language version, developer tools**
Rust

**OS/platform**
macOS ventura 13.2 
Darwin Kernel Version 22.3.0: Thu Jan  5 20:53:49 PST 2023; root:xnu-8792.81.2~2/RELEASE_X86_64 x86_64
rustc 1.67.0 (fc594f156 2023-01-24)
**Additional context**

**Comment by keelerm84** [comment]
I'm so sorry to hear you are running into compilation issues like this!

Does your application depend on an old version of `pin-project`? There [is an issue](https://github.com/taiki-e/pin-project/issues/337#issuecomment-1003328258) which sounds similar to the issue you are describing.

Testing this locally with a new binary application doesn't generate any errors, so it would also be helpful if we could get a list of project dependencies and versions to reproduce this locally.

**Comment by parallaxisjones** [comment]
Thank you for the reply! We are not directly using `pin-project`, my assumption is that it's used in tokio, which we're in turn using.

As for the other project dependencies, for testing and awareness sake --  If there is some way I can send to you directly the dependency set, as this is a proprietary work project, I would be willing to do that but I'm not sure sharing the whole set publicly on the gh issue is the right call there. I would have up front in the original post but thought twice about sharing publicly. 

FWIW I do think the problem is on our side, but embedded in an old version of a library we're utilizing proc macros from and unclear where exactly at the moment.

**Comment by keelerm84** [comment]
I can certainly appreciate that preference. You can email me directly if you want at `mkeeler@launchdarkly.com`.
