### ISSUE TITLE
SDK includes `hyper-rustls` and by extension `rustls` twice

### ISSUE THREAD

**Issue by lucacasonato** [launchdarkly/rust-server-sdk#42]
The SDK has a direct dependency on `hyper-rustls 0.23.0`. It also has a dependency on `eventsource-client 0.11.0`. `eventsource-client` has a dependency on `hyper-rustls 0.22.1`.

Also both of these `rustls` versions are out of date. The latest `hyper-rustls` is 0.24.0. Both dependencies should be updated to 0.24.0.

**Comment by keelerm84** [comment]
Thank you for opening this issue. We are aware of this dependency issue and will be working to fix it as soon as we are able.

We will update you here once this has been resolved.

**Comment by keelerm84** [comment]
v2 of the SDK was released which should have consistency dependencies between the event source and SDK.
