### ISSUE TITLE
Trim transitive dependencies - replace use of "built" crate with CARGO_PKG_VERSION

### ISSUE THREAD

**Issue by markdingram** [launchdarkly/rust-server-sdk#43]
**Is your feature request related to a problem? Please describe.**

This SDK currently uses "[built](https://crates.io/crates/built)" which has a few extra deps & a build script.

Appears lightly used:
https://github.com/launchdarkly/rust-server-sdk/blob/69cb1cc4c46ce9b1171769e3ede3ae88191507d8/launchdarkly-server-sdk/src/version.rs

 Seems like this could straightforwardly be replaced to reduce the transitive dependency impact on clients using this crate?

**Describe the solution you'd like**

Drop "built" crate, use Cargo variable CARGO_PKG_VERSION.

https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates

**Comment by keelerm84** [comment]
Thank you for raising this issue. I will take a look and update you once we have this resolved!

**Comment by keelerm84** [comment]
Addressed in 1.1.2. Thank you again for this issue!
