### ISSUE TITLE
Make dependency injection easier

### ISSUE THREAD

**Issue by mraerino** [launchdarkly/rust-server-sdk#5]
**Is your feature request related to a problem? Please describe.**

Most of the common building blocks should be abstracted as traits and made generic parameters in the structs and functions where they're used.

This improves the testability and allows flexibility for alternative implementations of certain parts (e.g. different stores).

**Describe the solution you'd like**

This could probably take a similar shape as in the Go SDK.

These come to mind:
- **Store**: Provides flags for evaluation ([example](https://github.com/mraerino/launchdarkly-rust-sdk-experimental/blob/main/src/store.rs#L18-L21))
- **Update Consumer**: Consumes updates from a stream - likely implemented for stores ([example](https://github.com/mraerino/launchdarkly-rust-sdk-experimental/blob/main/src/consumer.rs#L33-L56))
- **Update Source**: Provides a stream of updates ([example](https://github.com/mraerino/launchdarkly-rust-sdk-experimental/blob/main/src/source.rs#L16-L27))
- **Event Sink**: For sending events
- **Evaluator**: Turns flag & user into variation ([example](https://github.com/mraerino/launchdarkly-rust-sdk-experimental/blob/main/src/evaluator.rs#L277-L291))

**Describe alternatives you've considered**
n/a

**Additional context**

Pretty sure some of the proposed traits already exist.

**Comment by keelerm84** [comment]
With the latest beta release, each piece of the SDK that we allow to be swapped should have an associated trait for it. As we work towards a GA release, we might expand this to include additional traits.
