### ISSUE TITLE
Broken build: service_endpoints_trims_base_urls test

### ISSUE THREAD

**Issue by ramosbugs** [launchdarkly/rust-server-sdk#9]
**Is this a support request?**

No

**Describe the bug**

The CI and local builds are currently broken due to the `service_endpoints_trims_base_urls` test:
```
error: Test function service_endpoints_trims_base_urls has a return-type but no exected clause in the test-case. This is currently unsupported. See test-case documentation for more details.
   --> launchdarkly-server-sdk/src/service_endpoints.rs:165:10
    |
165 |     ) -> Result<(), Box<dyn std::error::Error>> {
    |          ^^^^^^

error: could not compile `launchdarkly-server-sdk` due to previous error
```

See https://app.circleci.com/pipelines/github/launchdarkly/rust-server-sdk/7/workflows/3bd8749c-8774-4e2c-ad03-0532aeef2585/jobs/7 for an example failed CI run.

**To reproduce**

Run `cargo check --all-targets`.

**Expected behavior**

Build succeeds without errors.

**Logs**

See above.

**SDK version**

`1.0.0-beta.2`

**Language version, developer tools**

```
cargo 1.58.0 (f01b232bc 2022-01-19)
rustc 1.58.1 (db9d1b20b 2022-01-20)
```

**OS/platform**

Mac OS 12.1 / CircleCI

**Comment by keelerm84** [comment]
This has been addressed. All tests should pass now.
